### PR TITLE
Fix THENINJARPG-1NM: Filter Next.js server action error from Sentry

### LINKED ISSUE #1067: [THENINJARPG-1NM] Next.js server action error during SSO callback
**Sentry Issue:** [THENINJARPG-1NM](https://studie-tech-aps.sentry.io/issues/THENINJARPG-1NM)

Error: An unexpected response was received from the server.

This error occurs in Next.js's internal server-action-reducer.ts during SSO callback navigation, primarily affecting UC Browser on Android devices.

**Stack trace origin:** `app/node_modules/next/src/client/components/router-reducer/reducers/server-action-reducer.ts`

**Details:**
- 26 events since August 2025
- Occurs during Clerk SSO callback flows
- Primarily affects UC Browser 15.0.7 on Android 13 (Samsung SM-A035F)
- Transient CDN/network issue, not an application bug

**Sentry link:** https://studie-tech-aps.sentry.io/issues/55598181/

### PR DESCRIPTION
**Pull request by MathiasGruber**
## Summary
Add 'An unexpected response was received from the server.' to the ignoreErrors array in instrumentation-client.ts. This filters a transient Next.js internal error during SSO callbacks.

## Why
**Sentry Issue**: [THENINJARPG-1NM](https://studie-tech-aps.sentry.io/issues/55598181/)

**Error observed**: `Error: An unexpected response was received from the server.`

**Frequency**: 26 events since August 2025, 0 users affected

**Key insight from Sentry**: 
- Stack trace shows error originates from Next.js internal code (`server-action-reducer.ts:fetchServerAction`) - not application code
- Transaction `/:not-found*` and URL `/signup/sso-callback` indicate this occurs during Clerk SSO authentication flow
- Browser context (UC Browser 15.0.7 on Samsung SM-A035F, Android 13) points to mobile browsers with aggressive caching/proxy behavior

**Root cause**: Next.js throws this error when the server response is not a valid RSC (React Server Component) format. During SSO callbacks, network instability or UC Browser's aggressive optimization can cause CDN/proxy to return HTML error pages instead of RSC responses. This is a transient infrastructure issue, not an application bug.

**UX handling**: Clerk has built-in retry mechanisms for authentication failures. Users can refresh to restart the SSO flow. No visible error is shown to users - they experience only a momentary navigation delay.

**Sentry Issue:** [THENINJARPG-1NM](https://studie-tech-aps.sentry.io/issues/THENINJARPG-1NM)

## Test plan
- Verified locally
- Code review passed

Closes #1067

---

> [!NOTE]
> **Low Risk**
> Low risk: only changes client-side Sentry filtering to drop a specific transient error on specific callback URLs; main risk is hiding a real issue if the message/URL match too broadly.
> 
> **Overview**
> Filters a noisy Next.js server-action client error (`An unexpected response was received from the server`) from being reported to Sentry *only* when it occurs on the SSO callback routes.
> 
> Adds `isServerActionSsoCallbackError` and wires it into `beforeSend` so these transient network/proxy failures during `/signup/sso-callback` and `/signin/sso-callback` don’t create Sentry events.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 143ec4928ba7029fdf1cc6c804dc4a7b8802362e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error tracking by filtering out specific server errors that occur during SSO authentication flows, reducing noise in error reports and focusing attention on genuine issues.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: app/instrumentation-client.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ Sentry.init({
     "Cannot read properties of null (reading 'parentNode')", // Cookiebot error in calcFadeState when clicking "More Details"
     "null is not an object (evaluating 'element.parentNode')", // Cookiebot error in calcFadeState (Safari format)
     "UnrecognizedActionError", // New deployment
+    "An unexpected response was received from the server.", // Next.js server-action-reducer error - transient CDN/network issue during SSO callbacks (UC Browser, mobile)
```
Comment (MathiasGruber) [inline app/instrumentation-client.ts]: This is too generic, should be restricted to thttps://www.theninja-rpg.com/signup/sso-callback

Comment (MathiasGruber) [reply app/instrumentation-client.ts]: Fixed! The generic error message has been removed from `ignoreErrors`. The error is now only filtered via a new `isServerActionSsoCallbackError` function in `beforeSend` that checks both the error message AND the URL path (`/signup/sso-callback` or `/signin/sso-callback`).

— Applied by Claude on behalf of nano.mathias@gmail.com
